server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: 1234
    username: manage_student
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true