server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: 123456
    username: assignment2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
